"use client";

import { useState } from "react";
import Image from "next/image";

const services = {
  "B2B SaaS": { title: "Software yang membuat tim bergerak lebih cepat.", copy: "Kami merancang platform yang kompleks jadi terasa sederhana—dari workspace multi-tenant sampai billing dan analytics.", tags: ["Multi-tenant", "Role & permission", "Admin dashboard", "Billing subscription"], icon: "▦" },
  "Consumer App": { title: "Produk digital yang ingin terus dipakai.", copy: "Bangun pengalaman yang intuitif dan berkesan untuk pengguna Anda, lengkap dengan fondasi yang siap tumbuh.", tags: ["Onboarding flow", "Social login", "Gamification", "Personalization"], icon: "✦" },
  "AI-powered": { title: "Ide AI, diwujudkan jadi produk nyata.", copy: "Dari prompt sampai production. Kami bantu menemukan use case AI yang tepat dan mengemasnya jadi workflow yang berguna.", tags: ["AI workflow", "RAG & knowledge base", "Prompt engineering", "Usage analytics"], icon: "ϟ" },
};
const faqs = [["Berapa lama proses pembuatan SaaS?", "Proyek rata-rata kami mulai dari 8–12 minggu untuk MVP yang solid. Durasi dapat berubah mengikuti kompleksitas dan kebutuhan integrasi."], ["Apakah bisa melanjutkan produk yang sudah ada?", "Tentu. Kami sering membantu audit, merapikan codebase, dan melanjutkan pengembangan produk yang sudah berjalan."], ["Teknologi apa yang digunakan?", "Kami menggunakan Flutter untuk membangun aplikasi multiplatform yang dapat berjalan di Android, iOS, web, dan desktop dengan satu codebase yang efisien."], ["Bagaimana cara memulai?", "Cukup ceritakan ide atau tantangan Anda melalui sesi discovery gratis. Kami akan bantu memetakan scope, prioritas, dan langkah berikutnya."]];
const Arrow = () => <span className="arrow">↗</span>;

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeService, setActiveService] = useState<keyof typeof services>("B2B SaaS");
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const service = services[activeService];
  return <main>
    <nav className="nav container"><a className="brand" href="#top"><Image className="brand-icon" src="/vertigo-icon.png" alt="Vertigo icon" width={32} height={32} priority /><Image className="brand-wordmark" src="/vertigo-text.png" alt="Vertigo" width={135} height={35} priority /></a><div className={`nav-links ${menuOpen ? "is-open" : ""}`}><a href="#layanan" onClick={() => setMenuOpen(false)}>Layanan</a><a href="#proses" onClick={() => setMenuOpen(false)}>Cara kerja</a><a href="#tentang" onClick={() => setMenuOpen(false)}>Tentang kami</a></div><a className="nav-cta" href="#kontak">Mulai proyek <Arrow /></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Buka menu">{menuOpen ? "×" : "☰"}</button></nav>
    <section className="hero container" id="top"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> Studio produk digital independen</div><h1>Bangun SaaS<br /><em>yang berarti.</em></h1><p className="hero-text">Kami membantu founder dan tim inovatif mengubah ide rumit menjadi produk digital yang dipakai, disukai, dan bertumbuh.</p><div className="hero-actions"><a className="button button-dark" href="#kontak">Ceritakan ide Anda <Arrow /></a><a className="text-link" href="#layanan">Lihat layanan <span>↓</span></a></div></div><div className="hero-art"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><div className="dashboard-card main-card"><div className="card-top"><Image className="mini-logo" src="/vertigo-icon.png" alt="" width={22} height={22} /><span>Overview</span><span className="card-more">•••</span></div><div className="metric-label">Monthly recurring revenue</div><div className="metric-value">$48,290 <span>↗ 18.4%</span></div><div className="chart"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><div className="chart-line" /></div><div className="chart-labels"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span></div></div><div className="float-card float-top"><span className="float-icon">↗</span><span><b>+24.8%</b><small>Growth this month</small></span></div><div className="float-card float-bottom"><div className="avatar-stack"><span>R</span><span>A</span><span>J</span></div><span><b>1,284 active users</b><small>Across 12 workspaces</small></span></div><div className="art-spark">✦</div></div></section>
    <section className="trusted container"><span>Dipercaya oleh tim yang ingin melangkah lebih jauh</span><div className="logo-row"><b>craft<span>work</span></b><b className="logo-serif">Luma</b><b className="logo-mono">POLARIS</b><b className="logo-serif italic">northstar</b><b className="logo-mono">vertex/</b></div></section>
    <section className="section services" id="layanan"><div className="container"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> Apa yang kami bangun</div><h2>Satu partner untuk<br /><em>seluruh perjalanan.</em></h2></div><p>Kami membangun berbagai solusi SaaS, mulai dari POS, ERP, CRM, HRIS, WMS, hingga platform custom sesuai kebutuhan bisnis Anda.</p></div><div className="service-tabs">{(Object.keys(services) as Array<keyof typeof services>).map((key, i) => <button key={key} className={activeService === key ? "active" : ""} onClick={() => setActiveService(key)}><span>0{i + 1}</span>{key}<Arrow /></button>)}</div><div className="service-panel"><div className="service-icon">{service.icon}</div><div><h3>{service.title}</h3><p>{service.copy}</p><div className="tag-list">{service.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div><div className="panel-arrow"><Arrow /></div></div></div></section>
    <section className="section process" id="proses"><div className="container"><div className="section-heading centered"><div><div className="eyebrow"><span className="eyebrow-line" /> Cara kerja kami</div><h2>Jelas dari awal,<br /><em>kuat sampai akhir.</em></h2></div><p>Kami percaya proses yang transparan menghasilkan produk yang lebih baik.</p></div><div className="process-grid">{[["01", "Discovery", "Kami memahami bisnis, pengguna, dan peluang yang ingin Anda menangkan."], ["02", "Design & build", "Ide berubah menjadi prototype lalu produk nyata melalui sprint yang terukur."], ["03", "Launch & grow", "Kami bantu meluncurkan, membaca data, dan terus mengembangkan produk."]].map(([num, title, text]) => <div className="process-card" key={num}><span className="process-num">{num}</span><div className="process-icon">{num === "01" ? "⌕" : num === "02" ? "◈" : "↗"}</div><h3>{title}</h3><p>{text}</p><a href="#kontak">Pelajari lebih lanjut <Arrow /></a></div>)}</div></div></section>
    <section className="quote-section" id="tentang"><div className="container quote-wrap"><div className="quote-mark">“</div><blockquote>Partner terbaik bukan yang hanya<br /> mengerjakan brief, tapi yang ikut<br /><em>memikirkan masa depan produk.</em></blockquote><div className="quote-author"><div className="author-avatar">DS</div><span><b>Dimas Saputra</b><small>Founder, Loka Studio</small></span></div></div></section>
    <section className="section faq"><div className="container faq-wrap"><div><div className="eyebrow"><span className="eyebrow-line" /> Pertanyaan umum</div><h2>Masih penasaran?<br /><em>Kami jawab.</em></h2><p>Kalau belum menemukan jawabannya, <a href="#kontak">sapa kami langsung <Arrow /></a></p></div><div className="faq-list">{faqs.map(([question, answer], i) => <div className={`faq-item ${openFaq === i ? "open" : ""}`} key={question}><button type="button" aria-expanded={openFaq === i} onClick={() => setOpenFaq(openFaq === i ? null : i)}><span>{question}</span><b aria-hidden="true">{openFaq === i ? "−" : "+"}</b></button>{openFaq === i && <p>{answer}</p>}</div>)}</div></div></section>
    <section className="contact container" id="kontak"><div className="contact-glow" /><div className="eyebrow"><span className="eyebrow-line" /> Mari mulai sesuatu</div><h2>Punya ide besar?<br /><em>Obrolkan dengan kami.</em></h2><p>Sesi konsultasi pertama selalu gratis. Tidak ada presentasi yang mengintimidasi—cukup cerita tentang apa yang ingin Anda bangun.</p><a className="button button-light" href="mailto:assistance.vertigo@gmail.com">Hubungi kami <Arrow /></a><div className="contact-note">Biasanya kami membalas dalam 1×24 jam</div></section>
    <footer className="footer container"><a className="brand" href="#top"><Image className="brand-icon" src="/vertigo-icon.png" alt="Vertigo icon" width={32} height={32} /><Image className="brand-wordmark" src="/vertigo-text.png" alt="Vertigo" width={135} height={35} /></a><span>© 2026 Vertigo Inc. Dibuat dengan niat baik.</span><div><a href="http://instagram.com/vertigo_saas" target="_blank" rel="noopener noreferrer">Instagram</a><a href="https://www.tiktok.com/@vertigo_saas" target="_blank" rel="noopener noreferrer">TikTok</a></div></footer>
  </main>;
}
